# THIS FILE HAS BEEN AUTOGENERATED. To update:
# 1. modify the `_deps` dict in setup.py
# 2. run `make deps_table_update``
deps = {
    "accelerate": "accelerate>=0.14.0",
    "torch": "torch>=1.9",
    "transformers": "transformers>=4.24.0",
    "black": "black==22.8",
    "isort": "isort>=5.5.4",
    "flake8": "flake8>=3.8.3",
    "numpy": "numpy",
    "filelock": "filelock",
    "importlib_metadata": "importlib_metadata",
    "datasets": "datasets>=2.7.0",
    "torchaudio": "torchaudio",
    "pyannote.audio": "pyannote.audio",
}
